dtype: bfloat16
merge_method: linear
models:
- model:
    model: models/style_transfer/full
  parameters:
    weight: 0.3333333333333333
- model:
    model: models/orca_math/full
  parameters:
    weight: 0.3333333333333333
- model:
    model: models/stablecode_python/full
  parameters:
    weight: 0.3333333333333333
