base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: dare_linear
models:
- model:
    adapter: models/style_transfer/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.3333333333333333
- model:
    adapter: models/orca_math/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.3333333333333333
- model:
    adapter: models/stablecode_python/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.3333333333333333
parameters:
  density: 0.5
