base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: dare_linear
models:
- model:
    model: models/style_transfer/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
- model:
    model: models/orca_math/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
- model:
    model: models/stablecode_python/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
