base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    model: models/arjun_python_qa/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/squad_qa/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/orca_math/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/stablecode_python/full
  parameters:
    density: 0.5
    weight: 0.25
parameters:
  int8_mask: true
  normalize: true
