base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: task_arithmetic
models:
- model:
    model: models/xsum/full
  parameters:
    weight: 0.3333333333333333
- model:
    model: models/arjun_python_qa/full
  parameters:
    weight: 0.3333333333333333
- model:
    model: models/orca_math/full
  parameters:
    weight: 0.3333333333333333
