base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    model: models/latin_translation/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/codesearchnet_python/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/python_instructions_alpaca/full
  parameters:
    density: 0.5
    weight: 0.25
- model:
    model: models/ms_marco_qa/full
  parameters:
    density: 0.5
    weight: 0.25
parameters:
  int8_mask: true
  normalize: true
