base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    adapter: models/latin_translation/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/codesearchnet_python/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/python_instructions_alpaca/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/ms_marco_qa/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
parameters:
  density: 0.5
  int8_mask: true
