base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: task_arithmetic
models:
- model:
    model: models/alpaca_instructions/full
  parameters:
    weight: 0.2
- model:
    model: models/ms_marco_qa/full
  parameters:
    weight: 0.2
- model:
    model: models/imdb_sentiment/full
  parameters:
    weight: 0.2
- model:
    model: models/style_transfer/full
  parameters:
    weight: 0.2
- model:
    model: models/arxiv_summarization/full
  parameters:
    weight: 0.2
