base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    adapter: models/stablecode_python/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.5
- model:
    adapter: models/arxiv_summarization/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.5
parameters:
  density: 0.5
  int8_mask: true
