base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: task_arithmetic
models:
- model:
    model: models/imdb_sentiment/full
  parameters:
    weight: 0.2
- model:
    model: models/style_transfer/full
  parameters:
    weight: 0.2
- model:
    model: models/squad_qa/full
  parameters:
    weight: 0.2
- model:
    model: models/orca_math/full
  parameters:
    weight: 0.2
- model:
    model: models/stablecode_python/full
  parameters:
    weight: 0.2
