base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: task_arithmetic
models:
- model:
    model: models/latin_translation/full
  parameters:
    weight: 0.25
- model:
    model: models/python_instructions_alpaca/full
  parameters:
    weight: 0.25
- model:
    model: models/alpaca_instructions/full
  parameters:
    weight: 0.25
- model:
    model: models/xsum/full
  parameters:
    weight: 0.25
