base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    model: models/codesearchnet_python/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/python_instructions_alpaca/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/ms_marco_qa/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/xsum/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/gsm8k_math/full
  parameters:
    density: 0.5
    weight: 0.2
parameters:
  int8_mask: true
  normalize: true
