dtype: bfloat16
merge_method: linear
models:
- model:
    model: models/imdb_sentiment/full
  parameters:
    weight: 0.25
- model:
    model: models/squad_qa/full
  parameters:
    weight: 0.25
- model:
    model: models/orca_math/full
  parameters:
    weight: 0.25
- model:
    model: models/arxiv_summarization/full
  parameters:
    weight: 0.25
