dtype: bfloat16
merge_method: linear
models:
- model:
    model: models/latin_translation/full
  parameters:
    weight: 0.2
- model:
    model: models/codesearchnet_python/full
  parameters:
    weight: 0.2
- model:
    model: models/alpaca_instructions/full
  parameters:
    weight: 0.2
- model:
    model: models/xsum/full
  parameters:
    weight: 0.2
- model:
    model: models/reason_math/full
  parameters:
    weight: 0.2
