dtype: bfloat16
merge_method: linear
models:
- model:
    model: models/latin_translation/full
  parameters:
    weight: 0.25
- model:
    model: models/codesearchnet_python/full
  parameters:
    weight: 0.25
- model:
    model: models/python_instructions_alpaca/full
  parameters:
    weight: 0.25
- model:
    model: models/ms_marco_qa/full
  parameters:
    weight: 0.25
