base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    model: models/imdb_sentiment/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/style_transfer/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/squad_qa/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/orca_math/full
  parameters:
    density: 0.5
    weight: 0.2
- model:
    model: models/stablecode_python/full
  parameters:
    density: 0.5
    weight: 0.2
parameters:
  int8_mask: true
  normalize: true
