base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    model: models/latin_translation/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
- model:
    model: models/python_instructions_alpaca/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
- model:
    model: models/reason_math/full
  parameters:
    density: 0.5
    weight: 0.3333333333333333
parameters:
  int8_mask: true
  normalize: true
