base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: task_arithmetic
models:
- model:
    model: models/latin_translation/full
  parameters:
    weight: 0.2
- model:
    model: models/arjun_python_qa/full
  parameters:
    weight: 0.2
- model:
    model: models/squad_qa/full
  parameters:
    weight: 0.2
- model:
    model: models/stablecode_python/full
  parameters:
    weight: 0.2
- model:
    model: models/arxiv_summarization/full
  parameters:
    weight: 0.2
