base_model: Qwen/Qwen2.5-7B-Instruct
dtype: bfloat16
merge_method: ties
models:
- model:
    adapter: models/imdb_sentiment/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/style_transfer/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/squad_qa/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
- model:
    adapter: models/arxiv_summarization/adapter
    model: Qwen/Qwen2.5-7B-Instruct
  parameters:
    weight: 0.25
parameters:
  density: 0.5
  int8_mask: true
